### ISSUE TITLE
一个小BUG

### ISSUE THREAD

**Issue by MissGongYi** [Ulez/DropIndicator#1]
当点击Indicator动画没结束时马上去点viewpager,动画结束时viewpager会停留在某个位置不回原位 比如1和4的切换

**Comment by Ulez** [comment]
源码里面Indicator动画没结束时是不能滑动viewpager的，我在属性动画结束时才把viewpager置为可触摸。但是为啥会发生这种情况不知道啥原理。设置可触摸取巧的设置了100毫秒的延时，现在应该没问题了。
